import { iconsImgs } from "../utils/images";
import { useLocation, useNavigate } from 'react-router-dom';
import "./AI_Insights.css";



const AI_Insides = () => {


    const location = useLocation();
     const navigate = useNavigate();
  return (
    <div className="grid-two-item grid-common grid-c7">
           
           <div className="grid-c-top text-silver-v7">
               <h2 className="lg-value">AI Insides</h2>
             

         {location.pathname !== "/ai-insights" && (
            <button className="grid-c-title-icon" onClick={() => navigate('/ai-insights')}>
            <img src={iconsImgs.plus} alt="Add" />
        </button>
            )}

           </div>
           <div className="grid-c7-content bg-jet">
               <div className="grid-items">
                   <div className="ai-container">
            <h1>AI Isights</h1>
      <p className="sub-title">Explore data-driven insights generated by our AI system.</p>

    
        <div className="insight-grid ${location.pathname === '/' ? 'limited' : ''}">
  <div className={`insight-grid ${location.pathname === "/" ? "limited" : ""}`}>
  <div className="insight-card">
    <h3>User Engagement</h3>
    <p>Engagement increased by <strong>23%</strong> over the past week.</p>
  </div>

  <div className="insight-card">
    <h3>Trending Topics</h3>
    <p>AI in Healthcare</p>
    <p>Machine Learning Models</p>
    <p>Chatbot Applications</p>
  </div>

  <div className="insight-card">
    <h3>Performance Alert</h3>
    <p>Prediction model accuracy dropped to <strong>89.5%</strong>. Consider retraining.</p>
  </div>

  <div className="insight-card">
    <h3>Smart Recommendations</h3>
    <p>Enable real-time analytics for better decision-making.</p>
  </div>
</div>

</div>

        
      
    </div>
               </div>
           </div>
       </div>
  )
}

export default AI_Insides
